INSERT INTO row
SELECT 
    '99-' || substr(idkey, 4, 12), /* idkey */ 
    file,
    '99. All', /* sheet */
    row,
    regiment,
    rank,
    name,
    person,
    page,
    deleted,
    handwritten,
    date,
    date2,
    annotations,
    reg_regiment,
    reg_rank,
    rank_lvl,
    surname,
    given,
    middlenames,
    title,
    namesuffix,
    nickname,
    fileyear,
    reg_date,
    link_category,
    link_score,
    link_log,
    row_count,
    reg_name,
    linked_to_file,
    linked_to_sheet,
    linked_to_row,
    linked_to_rowid,
    typev,
    reduced,
    datealt,
    companies,
    place,
    rank2,
    untitled,
    totheking,
    totheprince,
    rankunlisted,
    lv,
    sv,
    dv,
    othertext,
    role,
    medal,
    foreignorder,
    department,
    datefrom,
    dateto,
    regnumber,
    description,
    dategen,
    datelgen,
    datemgen,
    datecol,
    datelcol,
    datemaj,
    datefm,
    reg_date2,
    reg_date2rank,
    reg_date2lvl,
    reg_rank2,
    rank2_lvl,
    sheet, /* orig_sheet */
    idkey, /* orig_idkey */
    name_rank,
    name_rank_lvl
FROM row WHERE sheet IN (
    '10. Regiments',
    '11. Independent Companies',
    '12. Invalids',
    '14. Royal Artillery etc',
    '15. Marines',
    '16. Officers on Full Pay',
    '17-21. Military Departments',
    '22. Reduced Corps',
    '23. Companies of Foot',
    '24. Companies of Invalids',
    '25. Officers Unattached',
    '26. Foot Guards',
    '27. Retired & Reduced',
    '28-31. Officers on Half Pay',
    '32. New Independent Companies',
    '55. Fencibles',
    '56. Fencibles Handwritten'
);

