INSERT INTO row
SELECT 
    '99-' || substr(row.idkey, 4, 12), /* idkey */ 
    row.file,
    '99. All', /* sheet */
    row.row,
    row.regiment,
    row.rank,
    row.name,
    row.person,
    row.page,
    row.deleted,
    row.handwritten,
    row.date,
    row.date2,
    row.annotations,
    row.reg_regiment,
    row.reg_rank,
    row.rank_lvl,
    row.surname,
    row.given,
    row.middlenames,
    row.title,
    row.namesuffix,
    row.nickname,
    row.fileyear,
    row.reg_date,
    row.link_category,
    row.link_score,
    row.link_log,
    row.row_count,
    row.reg_name,
    row.linked_to_file,
    row.linked_to_sheet,
    row.linked_to_row,
    row.linked_to_rowid,
    row.typev,
    row.reduced,
    row.datealt,
    row.companies,
    row.place,
    row.rank2,
    row.untitled,
    row.totheking,
    row.totheprince,
    row.rankunlisted,
    row.lv,
    row.sv,
    row.dv,
    row.othertext,
    row.role,
    row.medal,
    row.foreignorder,
    row.department,
    row.datefrom,
    row.dateto,
    row.regnumber,
    row.description,
    row.dategen,
    row.datelgen,
    row.datemgen,
    row.datecol,
    row.datelcol,
    row.datemaj,
    row.datefm,
    row.reg_date2,
    row.reg_date2rank,
    row.reg_date2lvl,
    row.reg_rank2,
    row.rank2_lvl,
    row.sheet, /* orig_sheet */
    row.idkey, /* orig_idkey */
    row.name_rank,
    row.name_rank_lvl
FROM row
JOIN link ON row.idkey = link.aidkey
WHERE (link.link_category = 4 OR link.link_category = 6 OR link.link_category = 7)
AND sheet IN (
    '1. General and Field Officers',
    '4. Staff & Miscellaneous',
    '7. Order of the Bath',
    '8. Guelphic Order',
    '13. Garrisons',
    '35. Alterations While Printing',
	'61. General and Field Officers (handwritten)',
	'70. Regiments (handwritten)',
	'71. Independent Companies (handwritten)',
	'72. Invalids (handwritten)',
	'73. Garrisons (handwritten)',
	'74. Royal Artillery etc (handwritten)',
	'76. Officers on Full Pay (handwritten)',
	'82. Reduced Corps (handwritten)',
	'88-91. Officers on Half Pay (handwritten)',
	'92. New Independent Companies (handwritten)'
);

